apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: loan-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: loan/api-gateway:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: REDIS_URL
        - name: USER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: USER_SERVICE_URL
        - name: LOAN_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: LOAN_SERVICE_URL
        - name: REPAYMENT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: REPAYMENT_SERVICE_URL
        - name: RISK_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: RISK_SERVICE_URL
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: NOTIFICATION_SERVICE_URL
        - name: FILE_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: loan-config
              key: FILE_SERVICE_URL
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: loan-system
spec:
  selector:
    app: api-gateway
  ports:
  - port: 8000
    targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: loan-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80


