export default {
    'weixin': '\ue6a1',
    'camera': '\ue605',
    'headphones': '\ue630',
    'info': '\ue669',
    'locked': '\ue604',
    'wallet': '\ue608',
    'paperplane': '\ue64c',
    'shield-filled': '\ue80c',
    'personadd': '\ue612',
    'auth': '\ue6ab',
    'medal': '\ue6a5',
    'help': '\ue679',
    'refresh': '\ue635',
    'refreshempty': '\ue65e',
    'phone': '\ue622',
    'compose': '\ue67f',
    'warning': '\ue603',
    'person': '\ue607',
    'eye': '\ue602',
    'arrowright': '\ue601',
    'checkmarkempty': '\ue654',
} 