# 极速贷微服务系统 - Prometheus配置
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus自身监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # API网关监控
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 用户服务监控
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 贷款服务监控
  - job_name: 'loan-service'
    static_configs:
      - targets: ['loan-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 还款服务监控
  - job_name: 'repayment-service'
    static_configs:
      - targets: ['repayment-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 风控服务监控
  - job_name: 'risk-service'
    static_configs:
      - targets: ['risk-service:8004']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 通知服务监控
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8005']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # 文件服务监控
  - job_name: 'file-service'
    static_configs:
      - targets: ['file-service:8006']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # PostgreSQL数据库监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis缓存监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    scrape_timeout: 10s

  # MinIO对象存储监控
  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s
    scrape_timeout: 10s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s
    scrape_timeout: 10s